package gameengine

import (
	"strings"
	"testing"

	"github.com/hexdek/hexdek/internal/astload"
	"github.com/hexdek/hexdek/internal/gameast"
)

// -----------------------------------------------------------------------------
// r61.1 — cost-framework data contract, pinned against REAL parser output.
//
// The r61 PR-4/PR-5 suites built their Keyword fixtures by hand with
// float64 args — a shape the Python parser has never emitted — so they
// passed while every real card mispriced (kicker/overload/casualty fell
// back to card.CMC; buyback read empty args as free). These tests load
// the EXACT JSONL rows scripts/export_ast_dataset.py writes for four
// real cards (generated by the fixed parser, embedded verbatim below)
// through the production astload path, and drive the engine's actual
// CastSpell pipeline with them. If the parser's arg conventions and the
// engine's CostMeta/keyword readers ever drift apart again, these fail.
//
// Regenerate the fixture block after parser changes with:
//
//	python3 - <<'PY'
//	import sys, json; sys.path.insert(0, 'scripts')
//	import parser as P; P.load_extensions()
//	from export_ast_dataset import card_row
//	# ... card dicts as in scripts/check_ast_freshness.py docstring ...
//	PY
// -----------------------------------------------------------------------------

// realParserRowsR61 holds the verbatim export rows for Grunn, the Lonely
// King / Everflowing Chalice / Cyclonic Rift / Capsize, produced by the
// r61.1 parser (parse_keyword cost-arg capture + conditional_etb
// battlefield variant + p_tail_promoter kicked-ETB handler).
const realParserRowsR61 = `{"name": "Grunn, the Lonely King", "oracle_text": "Kicker {3} (You may pay an additional {3} as you cast this spell.)\nIf Grunn was kicked, it enters with five +1/+1 counters on it.\nWhenever Grunn attacks alone, double its power and toughness until end of turn.", "type_line": "Legendary Creature — Ape Warrior", "mana_cost": "{4}{G}{G}", "cmc": 6.0, "colors": ["G"], "ast": {"__ast_type__": "CardAST", "name": "Grunn, the Lonely King", "abilities": [{"__ast_type__": "Keyword", "name": "kicker", "args": ["{3}"], "raw": "kicker {3}"}, {"__ast_type__": "Static", "condition": {"__ast_type__": "Condition", "kind": "kicked", "args": [1]}, "modification": {"__ast_type__": "Modification", "kind": "etb_with_counters", "args": [5, "+1/+1"], "layer": null}, "raw": "if ~ was kicked, it enters with five +1/+1 counters on it"}, {"__ast_type__": "Triggered", "trigger": {"__ast_type__": "Trigger", "event": "attack_alone", "actor": null, "target_filter": null, "phase": null, "controller": null, "condition": null}, "effect": {"__ast_type__": "Buff", "kind": "buff", "power": "double", "toughness": "double", "target": {"__ast_type__": "Filter", "base": "creature", "quantifier": "one", "count": null, "targeted": true, "you_control": false, "opponent_controls": false, "nontoken": false, "creature_types": [], "color_filter": [], "color_exclude": [], "mana_value_op": null, "mana_value": null, "extra": []}, "duration": "until_end_of_turn"}, "intervening_if": null, "raw": "whenever ~ attacks alone, double its power and toughness until end of turn"}], "parse_errors": [], "fully_parsed": true, "morph_cost": null, "disguise_cost": null, "manifest_token": false, "has_morph": false, "has_megamorph": false, "has_disguise": false}}
{"name": "Everflowing Chalice", "oracle_text": "Multikicker {2} (You may pay an additional {2} any number of times as you cast this spell.)\nEverflowing Chalice enters the battlefield with a charge counter on it for each time it was kicked.\n{T}: Add {C} for each charge counter on Everflowing Chalice.", "type_line": "Artifact", "mana_cost": "{0}", "cmc": 0.0, "colors": [], "ast": {"__ast_type__": "CardAST", "name": "Everflowing Chalice", "abilities": [{"__ast_type__": "Keyword", "name": "multikicker", "args": ["{2}"], "raw": "multikicker {2}"}, {"__ast_type__": "Static", "condition": null, "modification": {"__ast_type__": "Modification", "kind": "etb_with_counters", "args": ["var", "charge", "for_each:time it was kicked"], "layer": null}, "raw": "~ enters the battlefield with a charge counter on it for each time it was kicked"}, {"__ast_type__": "Activated", "cost": {"__ast_type__": "Cost", "mana": null, "tap": true, "untap": false, "sacrifice": null, "discard": null, "pay_life": null, "exile_self": false, "return_self_to_hand": false, "remove_counters": null, "extra": []}, "effect": {"__ast_type__": "Modification", "kind": "add_mana_per", "args": ["{C}", "charge counter on ~"], "layer": null}, "timing_restriction": null, "raw": "{t}: add {c} for each charge counter on ~"}], "parse_errors": [], "fully_parsed": true, "morph_cost": null, "disguise_cost": null, "manifest_token": false, "has_morph": false, "has_megamorph": false, "has_disguise": false}}
{"name": "Cyclonic Rift", "oracle_text": "Return target nonland permanent you don't control to its owner's hand.\nOverload {6}{U} (You may cast this spell for its overload cost. If you do, change its text by replacing all instances of \"target\" with \"each.\")", "type_line": "Instant", "mana_cost": "{1}{U}", "cmc": 2.0, "colors": ["U"], "ast": {"__ast_type__": "CardAST", "name": "Cyclonic Rift", "abilities": [{"__ast_type__": "Static", "condition": null, "modification": {"__ast_type__": "Modification", "kind": "typed_spell_effect", "args": [{"__ast_type__": "Bounce", "kind": "bounce", "target": {"__ast_type__": "Filter", "base": "permanent", "quantifier": "one", "count": null, "targeted": true, "you_control": false, "opponent_controls": false, "nontoken": false, "creature_types": [], "color_filter": [], "color_exclude": [], "mana_value_op": null, "mana_value": null, "extra": ["non-land"]}, "to": "owners_hand"}], "layer": null}, "raw": "return target nonland permanent you don't control to its owner's hand"}, {"__ast_type__": "Keyword", "name": "overload", "args": ["{6}{u}"], "raw": "overload {6}{u}"}], "parse_errors": [], "fully_parsed": true, "morph_cost": null, "disguise_cost": null, "manifest_token": false, "has_morph": false, "has_megamorph": false, "has_disguise": false}}
{"name": "Capsize", "oracle_text": "Buyback {3} (You may pay an additional {3} as you cast this spell. If you do, put this card into your hand as it resolves.)\nReturn target permanent to its owner’s hand.", "type_line": "Instant", "mana_cost": "{1}{U}{U}", "cmc": 3.0, "colors": ["U"], "ast": {"__ast_type__": "CardAST", "name": "Capsize", "abilities": [{"__ast_type__": "Keyword", "name": "buyback", "args": ["{3}"], "raw": "buyback {3}"}, {"__ast_type__": "Static", "condition": null, "modification": {"__ast_type__": "Modification", "kind": "typed_spell_effect", "args": [{"__ast_type__": "Modification", "kind": "parsed_effect_residual", "args": ["return target permanent to its owner’s hand"], "layer": null}], "layer": null}, "raw": "return target permanent to its owner’s hand"}], "parse_errors": [], "fully_parsed": true, "morph_cost": null, "disguise_cost": null, "manifest_token": false, "has_morph": false, "has_megamorph": false, "has_disguise": false}}`

func loadRealCorpusR61(t *testing.T) *astload.Corpus {
	t.Helper()
	corpus, err := astload.LoadReader(strings.NewReader(realParserRowsR61))
	if err != nil {
		t.Fatalf("LoadReader: %v", err)
	}
	if corpus.CardCount != 4 {
		t.Fatalf("expected 4 fixture cards, got %d (warnings: %v)",
			corpus.CardCount, corpus.ParseWarnings)
	}
	return corpus
}

// realCardR61 mirrors deckparser.buildCard: AST from the corpus, metadata
// (types / CMC / P-T / colors) from the oracle row — the same split
// production uses.
func realCardR61(t *testing.T, corpus *astload.Corpus, name string,
	types []string, cmc, pow, tough int, colors []string) *Card {
	t.Helper()
	ast, ok := corpus.Get(name)
	if !ok || ast == nil {
		t.Fatalf("fixture corpus missing %q", name)
	}
	return &Card{
		Name:          name,
		AST:           ast,
		Types:         types,
		CMC:           cmc,
		BasePower:     pow,
		BaseToughness: tough,
		Colors:        colors,
		Owner:         0,
	}
}

// --- Cost readers against the real parsed shapes ---------------------------

func TestRealAST_CostReaders(t *testing.T) {
	corpus := loadRealCorpusR61(t)
	grunn := realCardR61(t, corpus, "Grunn, the Lonely King",
		[]string{"creature"}, 6, 5, 5, []string{"G"})
	chalice := realCardR61(t, corpus, "Everflowing Chalice",
		[]string{"artifact"}, 0, 0, 0, nil)
	rift := realCardR61(t, corpus, "Cyclonic Rift",
		[]string{"instant"}, 2, 0, 0, []string{"U"})
	capsize := realCardR61(t, corpus, "Capsize",
		[]string{"instant"}, 3, 0, 0, []string{"U"})

	if got := KickerCost(grunn); got != 3 {
		t.Errorf("Grunn KickerCost = %d, want 3 (kicker {3}); pre-r61.1 the CMC fallback returned 6", got)
	}
	if !IsMultikicker(chalice) {
		t.Errorf("Chalice should be multikicker")
	}
	if got := KickerCost(chalice); got != 2 {
		t.Errorf("Chalice KickerCost = %d, want 2 (multikicker {2}); pre-r61.1 the CMC fallback returned 0", got)
	}
	if got := OverloadCost(rift); got != 7 {
		t.Errorf("Cyclonic Rift OverloadCost = %d, want 7 ({6}{U}); pre-r61.1 the CMC fallback returned 2", got)
	}
	if got := BuybackCost(capsize); got != 3 {
		t.Errorf("Capsize BuybackCost = %d, want 3 (buyback {3}); pre-r61.1 empty args read as 0 = free", got)
	}
}

// --- Kicked Grunn through the real cast pipeline ----------------------------

func TestRealAST_Grunn_Kicked_Enters10_10_With5Counters(t *testing.T) {
	corpus := loadRealCorpusR61(t)
	gs := newFixtureGame(t)
	gs.Seats[0].Hat = &kickHat{}
	gs.Seats[0].ManaPool = 9 // 6 base + 3 kicker
	card := realCardR61(t, corpus, "Grunn, the Lonely King",
		[]string{"creature"}, 6, 5, 5, []string{"G"})
	gs.Seats[0].Hand = []*Card{card}

	if err := CastSpell(gs, 0, card, nil); err != nil {
		t.Fatalf("CastSpell failed: %v", err)
	}
	perm := castOnlyPerm(gs, 0)
	if perm == nil {
		t.Fatalf("Grunn not on battlefield")
	}
	if perm.Flags["kicked"] < 1 {
		t.Errorf("expected kicked flag >= 1, got %d", perm.Flags["kicked"])
	}
	if perm.Counters["+1/+1"] != 5 {
		t.Errorf("kicked Grunn should have 5 +1/+1 counters, got %d", perm.Counters["+1/+1"])
	}
	if gs.PowerOf(perm) != 10 || gs.ToughnessOf(perm) != 10 {
		t.Errorf("kicked Grunn should be 10/10, got %d/%d",
			gs.PowerOf(perm), gs.ToughnessOf(perm))
	}
	if gs.Seats[0].ManaPool != 0 {
		t.Errorf("expected 9 mana spent (6 base + 3 kicker), pool = %d", gs.Seats[0].ManaPool)
	}
}

func TestRealAST_Grunn_Unkicked_Enters5_5_NoCounters(t *testing.T) {
	corpus := loadRealCorpusR61(t)
	gs := newFixtureGame(t)
	gs.Seats[0].Hat = &noKickHat{}
	gs.Seats[0].ManaPool = 9
	card := realCardR61(t, corpus, "Grunn, the Lonely King",
		[]string{"creature"}, 6, 5, 5, []string{"G"})
	gs.Seats[0].Hand = []*Card{card}

	if err := CastSpell(gs, 0, card, nil); err != nil {
		t.Fatalf("CastSpell failed: %v", err)
	}
	perm := castOnlyPerm(gs, 0)
	if perm == nil {
		t.Fatalf("Grunn not on battlefield")
	}
	if perm.Counters["+1/+1"] != 0 {
		t.Errorf("unkicked Grunn should have 0 counters, got %d — the kicked condition was not honored", perm.Counters["+1/+1"])
	}
	if gs.PowerOf(perm) != 5 || gs.ToughnessOf(perm) != 5 {
		t.Errorf("unkicked Grunn should be 5/5, got %d/%d",
			gs.PowerOf(perm), gs.ToughnessOf(perm))
	}
}

// --- Multikicked Chalice through the real cast pipeline ---------------------

func TestRealAST_Chalice_MultikickedTwice_TwoChargeCounters(t *testing.T) {
	corpus := loadRealCorpusR61(t)
	gs := newFixtureGame(t)
	gs.Seats[0].Hat = &kickHat{} // pays max affordable kicks
	gs.Seats[0].ManaPool = 4     // 0 base + 2 kicks x {2}
	card := realCardR61(t, corpus, "Everflowing Chalice",
		[]string{"artifact"}, 0, 0, 0, nil)
	gs.Seats[0].Hand = []*Card{card}

	if err := CastSpell(gs, 0, card, nil); err != nil {
		t.Fatalf("CastSpell failed: %v", err)
	}
	perm := castOnlyPerm(gs, 0)
	if perm == nil {
		t.Fatalf("Chalice not on battlefield")
	}
	if perm.Counters["charge"] != 2 {
		t.Errorf("twice-multikicked Chalice should have 2 charge counters, got %d (multikick_count flag=%d)",
			perm.Counters["charge"], perm.Flags["multikick_count"])
	}
	if gs.Seats[0].ManaPool != 0 {
		t.Errorf("expected 4 mana spent on 2 kicks, pool = %d", gs.Seats[0].ManaPool)
	}
}

func TestRealAST_Chalice_Unkicked_ZeroCounters(t *testing.T) {
	corpus := loadRealCorpusR61(t)
	gs := newFixtureGame(t)
	gs.Seats[0].Hat = &noKickHat{}
	gs.Seats[0].ManaPool = 4
	card := realCardR61(t, corpus, "Everflowing Chalice",
		[]string{"artifact"}, 0, 0, 0, nil)
	gs.Seats[0].Hand = []*Card{card}

	if err := CastSpell(gs, 0, card, nil); err != nil {
		t.Fatalf("CastSpell failed: %v", err)
	}
	perm := castOnlyPerm(gs, 0)
	if perm == nil {
		t.Fatalf("Chalice not on battlefield")
	}
	if perm.Counters["charge"] != 0 {
		t.Errorf("unkicked Chalice should have 0 charge counters, got %d", perm.Counters["charge"])
	}
}

// --- Decline-on-unknown: empty args must never read as free ------------------

func TestRealAST_EmptyArgs_DeclineNotFree(t *testing.T) {
	// A keyword node with NO cost arg (the pre-r61.1 parser emitted this
	// for every single-pip cost). The strict readers must return 0 and
	// the gates must treat 0 as decline.
	card := &Card{
		Name:  "Argless Buyback Test",
		Types: []string{"instant"},
		CMC:   4,
		AST:   mustASTWithArglessKeyword(t, "buyback"),
	}
	if got := BuybackCost(card); got != 0 {
		t.Errorf("BuybackCost with empty args = %d, want 0", got)
	}
	card2 := &Card{
		Name:  "Argless Overload Test",
		Types: []string{"instant"},
		CMC:   2,
		AST:   mustASTWithArglessKeyword(t, "overload"),
	}
	if got := OverloadCost(card2); got != 0 {
		t.Errorf("OverloadCost with empty args = %d, want 0 (decline), not CMC %d", got, card2.CMC)
	}
	card3 := &Card{
		Name:  "Argless Casualty Test",
		Types: []string{"sorcery"},
		CMC:   4,
		AST:   mustASTWithArglessKeyword(t, "casualty"),
	}
	if got := CasualtyMinPower(card3); got != 0 {
		t.Errorf("CasualtyMinPower with empty args = %d, want 0 (decline), not CMC %d", got, card3.CMC)
	}
	card4 := &Card{
		Name:  "Argless Kicker Test",
		Types: []string{"creature"},
		CMC:   6,
		AST:   mustASTWithArglessKeyword(t, "kicker"),
	}
	if got := KickerCost(card4); got != 0 {
		t.Errorf("KickerCost with empty args = %d, want 0 (decline), not CMC %d", got, card4.CMC)
	}
}

// mustASTWithArglessKeyword builds a minimal CardAST whose only ability
// is the named keyword with NO args — the shape the pre-r61.1 parser
// emitted for every single-pip keyword cost.
func mustASTWithArglessKeyword(t *testing.T, kw string) *gameast.CardAST {
	t.Helper()
	return &gameast.CardAST{
		Name: "argless-" + kw,
		Abilities: []gameast.Ability{
			&gameast.Keyword{Name: kw},
		},
	}
}
