package gameengine

import (
	"math/rand"
	"testing"
)

// r63 regenerate probe — CR §701.15 regeneration as a replacement shield.
// Focus: "can't be regenerated" (§701.15g, Wrath of God / Damnation) must
// bypass the shield, and the zero-toughness SBA (§704.5f, "put into
// graveyard", NOT a destroy) must NOT be replaced by regeneration — while
// lethal-damage (§704.5g) MUST be.

func rg_game() *GameState { return NewGameState(2, rand.New(rand.NewSource(3)), nil) }

func rg_creature(gs *GameState, seat int, name string, pow, tough int) *Permanent {
	p := &Permanent{
		Card:       &Card{Name: name, Owner: seat, Types: []string{"creature"}, BasePower: pow, BaseToughness: tough},
		Controller: seat, Owner: seat, Timestamp: gs.NextTimestamp(),
		Counters: map[string]int{}, Flags: map[string]int{},
	}
	gs.Seats[seat].Battlefield = append(gs.Seats[seat].Battlefield, p)
	return p
}

func rg_inGraveyard(gs *GameState, seat int, name string) bool {
	for _, c := range gs.Seats[seat].Graveyard {
		if c != nil && c.DisplayName() == name {
			return true
		}
	}
	return false
}

func rg_onBattlefield(gs *GameState, p *Permanent) bool {
	for _, q := range gs.Seats[p.Controller].Battlefield {
		if q == p {
			return true
		}
	}
	return false
}

// (b) A normal destroy effect IS replaced by a regeneration shield.
func TestRegen_NormalDestroyRegenerates(t *testing.T) {
	gs := rg_game()
	c := rg_creature(gs, 0, "Drudge Skeletons", 1, 1)
	GrantRegenerationShield(gs, c)
	c.MarkedDamage = 5
	c.Tapped = false
	setPermFlag(c, flagAttacking, true)

	if DestroyPermanent(gs, c, nil) {
		t.Fatal("a regen shield must replace a normal destroy (return false)")
	}
	if !rg_onBattlefield(gs, c) {
		t.Error("regenerated creature must stay on the battlefield")
	}
	if !c.Tapped || c.MarkedDamage != 0 || c.IsAttacking() {
		t.Errorf("regen must tap, clear damage, and remove from combat; tapped=%v dmg=%d atk=%v",
			c.Tapped, c.MarkedDamage, c.IsAttacking())
	}
	if c.Flags["regeneration_shield"] != 0 {
		t.Errorf("the shield must be consumed, got %d", c.Flags["regeneration_shield"])
	}
}

// (c) "Can't be regenerated" destruction bypasses the shield.
func TestRegen_CantBeRegeneratedBypassesShield(t *testing.T) {
	gs := rg_game()
	c := rg_creature(gs, 0, "Drudge Skeletons", 1, 1)
	GrantRegenerationShield(gs, c)

	if !DestroyPermanentNoRegen(gs, c, nil) {
		t.Fatal("DestroyPermanentNoRegen must destroy despite a regen shield (return true)")
	}
	if rg_onBattlefield(gs, c) {
		t.Error("a 'can't be regenerated' destroy must not leave the creature on the battlefield")
	}
	if !rg_inGraveyard(gs, 0, "Drudge Skeletons") {
		t.Error("the creature must be in the graveyard")
	}
}

// (c) Indestructible still survives a "can't be regenerated" wipe.
func TestRegen_NoRegenStillRespectsIndestructible(t *testing.T) {
	gs := rg_game()
	c := rg_creature(gs, 0, "Darksteel Myr", 0, 1)
	c.Flags["kw:indestructible"] = 1
	GrantRegenerationShield(gs, c)

	if DestroyPermanentNoRegen(gs, c, nil) {
		t.Fatal("indestructible must survive even a can't-be-regenerated destroy")
	}
	if !rg_onBattlefield(gs, c) {
		t.Error("indestructible creature must remain on the battlefield")
	}
}

// (e) Multiple shields stack — each replaces one destroy.
func TestRegen_ShieldsStack(t *testing.T) {
	gs := rg_game()
	c := rg_creature(gs, 0, "Drudge Skeletons", 1, 1)
	GrantRegenerationShield(gs, c)
	GrantRegenerationShield(gs, c)

	if DestroyPermanent(gs, c, nil) {
		t.Fatal("first destroy should be regenerated")
	}
	if c.Flags["regeneration_shield"] != 1 {
		t.Errorf("one shield should remain, got %d", c.Flags["regeneration_shield"])
	}
	if DestroyPermanent(gs, c, nil) {
		t.Fatal("second destroy should be regenerated by the second shield")
	}
	// Third destroy: no shield left.
	if !DestroyPermanent(gs, c, nil) {
		t.Error("with no shields left, the creature should finally be destroyed")
	}
}

// (c) CRITICAL: zero-toughness SBA (§704.5f) is "put into graveyard", NOT a
// destroy — a regen shield must NOT save it.
func TestRegen_ZeroToughnessSBANotRegenerated(t *testing.T) {
	gs := rg_game()
	c := rg_creature(gs, 0, "Doomed Bear", 2, 2)
	GrantRegenerationShield(gs, c)
	// -2/-2 makes toughness 0 → §704.5f.
	c.Modifications = append(c.Modifications, Modification{Power: -2, Toughness: -2,
		Duration: "until_end_of_turn", Timestamp: gs.NextTimestamp()})
	gs.InvalidateCharacteristicsCache()

	StateBasedActions(gs)

	if rg_onBattlefield(gs, c) {
		t.Error("a 0-toughness creature must be put into the graveyard; regen must NOT save it (§704.5f)")
	}
	if !rg_inGraveyard(gs, 0, "Doomed Bear") {
		t.Error("0-toughness creature must be in the graveyard")
	}
}

// (b)/(d) lethal-damage SBA (§704.5g) IS replaced by regeneration.
func TestRegen_LethalDamageSBARegenerates(t *testing.T) {
	gs := rg_game()
	c := rg_creature(gs, 0, "Drudge Skeletons", 1, 1)
	GrantRegenerationShield(gs, c)
	c.MarkedDamage = c.Toughness() // lethal

	StateBasedActions(gs)

	if !rg_onBattlefield(gs, c) {
		t.Error("lethal-damage destruction must be replaced by regeneration (creature stays)")
	}
	if !c.Tapped || c.MarkedDamage != 0 {
		t.Errorf("regen must tap + clear damage; tapped=%v dmg=%d", c.Tapped, c.MarkedDamage)
	}
	if c.Flags["regeneration_shield"] != 0 {
		t.Errorf("shield must be consumed, got %d", c.Flags["regeneration_shield"])
	}
}
