// audit-test-coverage — Parse a Go test coverage profile, aggregate by
// package and by file, and emit a markdown report that flags
// undertested packages and never-tested files.
//
// Inputs:
//
//	--profile <path>   coverage profile generated by `go test -coverprofile=...`
//	--out <path>       markdown report output path
//	--threshold <pct>  packages strictly below this percentage are flagged
//	                   "undertested" (default 50)
//	--module <path>    module import prefix; trimmed from filenames for
//	                   prettier display (default "github.com/hexdek/hexdek")
//
// Findings-only — the tool never mutates source. Coverage profile
// format reference: https://pkg.go.dev/golang.org/x/tools/cover.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path"
	"sort"
	"strings"
)

func main() {
	profile := flag.String("profile", "cover.out", "coverage profile path (from `go test -coverprofile=...`)")
	outPath := flag.String("out", "docs/test-coverage-audit-r60.md", "markdown report output path")
	threshold := flag.Float64("threshold", 50.0, "packages strictly below this coverage percentage are flagged undertested")
	module := flag.String("module", "github.com/hexdek/hexdek", "module import prefix trimmed from filenames for display")
	flag.Parse()

	data, err := os.ReadFile(*profile)
	if err != nil {
		log.Fatalf("read profile %q: %v", *profile, err)
	}

	report, err := analyze(string(data), *module, *threshold)
	if err != nil {
		log.Fatalf("analyze: %v", err)
	}

	md := renderMarkdown(report, *threshold)
	if err := os.WriteFile(*outPath, []byte(md), 0o644); err != nil {
		log.Fatalf("write report %q: %v", *outPath, err)
	}

	fmt.Printf("Report written: %s\n", *outPath)
	fmt.Printf("  %d packages analyzed, %d undertested (<%.0f%%)\n",
		len(report.Packages), len(report.UndertestedPackages), *threshold)
	fmt.Printf("  %d files analyzed, %d never-tested (0%% coverage)\n",
		len(report.Files), len(report.NeverTestedFiles))
}

// FileCoverage holds the aggregated coverage stats for one source file.
type FileCoverage struct {
	Path       string  // relative path (module prefix stripped)
	Package    string  // package directory (relative)
	Statements int     // total statements
	Covered    int     // statements with hits > 0
	Percent    float64 // 100 * Covered/Statements (0 when Statements == 0)
}

// PackageCoverage aggregates the per-file stats up to the directory
// level. A "package" here is the import-path directory; Go's coverprofile
// emits one record per (file, block) where every file's directory is
// the package directory.
type PackageCoverage struct {
	Path       string
	Statements int
	Covered    int
	Percent    float64
	Files      []FileCoverage
}

// Report is the analysis output passed to the markdown renderer.
type Report struct {
	OverallStatements   int
	OverallCovered      int
	OverallPercent      float64
	Packages            []PackageCoverage
	Files               []FileCoverage
	UndertestedPackages []PackageCoverage // sorted ascending by Percent
	NeverTestedFiles    []FileCoverage    // sorted by Path
}

// analyze parses the coverage profile body and aggregates to per-file
// and per-package totals. Profile format reference:
//
//	mode: set|count|atomic
//	<filename>:<startLine>.<startCol>,<endLine>.<endCol> <numStmt> <count>
//
// numStmt is the statements in the block; count is the hit count for
// "set" mode it's 0 or 1, for "count"/"atomic" it's a real frequency.
// We treat "covered" as count > 0, so the percentage is the fraction
// of statements ever executed regardless of mode.
func analyze(body, module string, threshold float64) (*Report, error) {
	lines := strings.Split(body, "\n")
	if len(lines) == 0 {
		return nil, fmt.Errorf("empty profile")
	}

	// Aggregate per file. Each profile entry contributes numStmt to the
	// file's total; if count > 0 we add numStmt to Covered. (Each block
	// is either fully covered or fully uncovered in "set" mode; in
	// "count"/"atomic" any nonzero count means the statements ran at
	// least once, which is what the percentage measures.)
	fileStats := map[string]*FileCoverage{}
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "mode:") {
			continue
		}
		// Format: <file>:<startLine>.<startCol>,<endLine>.<endCol> <numStmt> <count>
		colon := strings.LastIndex(line, ":")
		if colon < 0 {
			continue
		}
		filename := line[:colon]
		rest := line[colon+1:]
		fields := strings.Fields(rest)
		if len(fields) < 3 {
			continue
		}
		var numStmt, count int
		if _, err := fmt.Sscanf(fields[len(fields)-2], "%d", &numStmt); err != nil {
			continue
		}
		if _, err := fmt.Sscanf(fields[len(fields)-1], "%d", &count); err != nil {
			continue
		}

		display := strings.TrimPrefix(filename, module+"/")

		fc, ok := fileStats[display]
		if !ok {
			fc = &FileCoverage{
				Path:    display,
				Package: path.Dir(display),
			}
			fileStats[display] = fc
		}
		fc.Statements += numStmt
		if count > 0 {
			fc.Covered += numStmt
		}
	}

	if len(fileStats) == 0 {
		return nil, fmt.Errorf("no coverage records parsed from profile")
	}

	// Files slice, sorted by path.
	files := make([]FileCoverage, 0, len(fileStats))
	for _, fc := range fileStats {
		if fc.Statements > 0 {
			fc.Percent = 100.0 * float64(fc.Covered) / float64(fc.Statements)
		}
		files = append(files, *fc)
	}
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })

	// Aggregate to package directories.
	pkgMap := map[string]*PackageCoverage{}
	for _, fc := range files {
		pc, ok := pkgMap[fc.Package]
		if !ok {
			pc = &PackageCoverage{Path: fc.Package}
			pkgMap[fc.Package] = pc
		}
		pc.Statements += fc.Statements
		pc.Covered += fc.Covered
		pc.Files = append(pc.Files, fc)
	}
	packages := make([]PackageCoverage, 0, len(pkgMap))
	for _, pc := range pkgMap {
		if pc.Statements > 0 {
			pc.Percent = 100.0 * float64(pc.Covered) / float64(pc.Statements)
		}
		sort.Slice(pc.Files, func(i, j int) bool { return pc.Files[i].Path < pc.Files[j].Path })
		packages = append(packages, *pc)
	}
	sort.Slice(packages, func(i, j int) bool { return packages[i].Path < packages[j].Path })

	// Build undertested + never-tested slices.
	var underPkgs []PackageCoverage
	for _, p := range packages {
		if p.Statements > 0 && p.Percent < threshold {
			underPkgs = append(underPkgs, p)
		}
	}
	sort.Slice(underPkgs, func(i, j int) bool { return underPkgs[i].Percent < underPkgs[j].Percent })

	var neverFiles []FileCoverage
	for _, f := range files {
		if f.Statements > 0 && f.Covered == 0 {
			neverFiles = append(neverFiles, f)
		}
	}
	sort.Slice(neverFiles, func(i, j int) bool { return neverFiles[i].Path < neverFiles[j].Path })

	rep := &Report{
		Packages:            packages,
		Files:               files,
		UndertestedPackages: underPkgs,
		NeverTestedFiles:    neverFiles,
	}
	for _, p := range packages {
		rep.OverallStatements += p.Statements
		rep.OverallCovered += p.Covered
	}
	if rep.OverallStatements > 0 {
		rep.OverallPercent = 100.0 * float64(rep.OverallCovered) / float64(rep.OverallStatements)
	}
	return rep, nil
}

// recommend returns a short per-file recommendation string keyed off
// the file's path prefix and coverage percent. The categories match the
// architecture-aware buckets the user cares about: engine paths,
// hexapi handlers, AI logic, CLI entry points, and generic internal/
// utilities. Coverage band tunes the recommendation severity.
func recommend(f FileCoverage) string {
	band := "minimal coverage — backfill primary path"
	switch {
	case f.Percent == 0:
		band = "never tested — add at minimum a happy-path test"
	case f.Percent < 25:
		band = "minimal coverage — backfill primary path"
	case f.Percent < 50:
		band = "below threshold — backfill edge cases"
	}

	p := f.Path
	switch {
	case strings.HasPrefix(p, "internal/gameengine/per_card/"):
		return band + "; per-card handler — pair with a per_card_*_test.go regression in the same dir"
	case strings.HasPrefix(p, "internal/gameengine/"):
		return band + "; core engine path — high-priority, exercises rules code"
	case strings.HasPrefix(p, "internal/hexapi/"):
		return band + "; HTTP/WS handler — add an endpoint integration test"
	case strings.HasPrefix(p, "internal/hat/"):
		return band + "; AI decision logic — add a focused MCTS / heuristic test"
	case strings.HasPrefix(p, "internal/analytics/"):
		return band + "; Heimdall analytics — add a replay-fixture test"
	case strings.HasPrefix(p, "internal/tournament/"):
		return band + "; tournament runner — add a small-N pool simulation test"
	case strings.HasPrefix(p, "internal/gameast/"):
		return band + "; AST parser — add a representative card-text round-trip test"
	case strings.HasPrefix(p, "internal/"):
		return band + "; internal utility — add unit tests for the public surface"
	case strings.HasPrefix(p, "cmd/"):
		return band + "; CLI entry point — consider integration smoke test or extract logic to a tested helper"
	default:
		return band
	}
}

// renderMarkdown turns the analysis Report into the markdown document
// written to disk. Sections (in order):
//
//	1. Overall summary (totals + overall %)
//	2. Undertested packages (sorted ascending by % so the most-needy
//	   shows first)
//	3. Never-tested files (0% — alphabetical for stable diffs)
//	4. Per-file recommendations (alphabetical) — bands files by
//	   coverage tier and provides architecture-aware suggestions
func renderMarkdown(r *Report, threshold float64) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Test Coverage Audit (r60)\n\n")
	fmt.Fprintf(&b, "_Generated by `cmd/audit-test-coverage` from a `go test -coverprofile=...` run._\n\n")
	fmt.Fprintf(&b, "## Overall\n\n")
	fmt.Fprintf(&b, "- **Total packages analyzed:** %d\n", len(r.Packages))
	fmt.Fprintf(&b, "- **Total files analyzed:** %d\n", len(r.Files))
	fmt.Fprintf(&b, "- **Total statements:** %d\n", r.OverallStatements)
	fmt.Fprintf(&b, "- **Total covered:** %d (%.1f%%)\n", r.OverallCovered, r.OverallPercent)
	fmt.Fprintf(&b, "- **Undertested packages (<%.0f%%):** %d\n", threshold, len(r.UndertestedPackages))
	fmt.Fprintf(&b, "- **Never-tested files (0%%):** %d\n\n", len(r.NeverTestedFiles))

	fmt.Fprintf(&b, "## Undertested Packages (<%.0f%% statement coverage)\n\n", threshold)
	if len(r.UndertestedPackages) == 0 {
		fmt.Fprintf(&b, "_None — every package meets the threshold._\n\n")
	} else {
		fmt.Fprintf(&b, "Sorted ascending by coverage; lowest-coverage packages first.\n\n")
		fmt.Fprintf(&b, "| Package | Coverage | Covered / Total | Files |\n")
		fmt.Fprintf(&b, "|---|---:|---:|---:|\n")
		for _, p := range r.UndertestedPackages {
			fmt.Fprintf(&b, "| `%s` | %.1f%% | %d / %d | %d |\n",
				p.Path, p.Percent, p.Covered, p.Statements, len(p.Files))
		}
		fmt.Fprintln(&b)
	}

	fmt.Fprintf(&b, "## Never-Tested Files (0%% statement coverage)\n\n")
	if len(r.NeverTestedFiles) == 0 {
		fmt.Fprintf(&b, "_None — every file with statements has at least one block executed._\n\n")
	} else {
		fmt.Fprintf(&b, "Production source files where every block missed in this run. Sorted alphabetically.\n\n")
		fmt.Fprintf(&b, "| File | Statements |\n")
		fmt.Fprintf(&b, "|---|---:|\n")
		for _, f := range r.NeverTestedFiles {
			fmt.Fprintf(&b, "| `%s` | %d |\n", f.Path, f.Statements)
		}
		fmt.Fprintln(&b)
	}

	fmt.Fprintf(&b, "## Per-File Recommendations\n\n")
	// Render only files that need attention: 0% OR < threshold.
	var attention []FileCoverage
	for _, f := range r.Files {
		if f.Statements == 0 {
			continue
		}
		if f.Percent < threshold {
			attention = append(attention, f)
		}
	}
	if len(attention) == 0 {
		fmt.Fprintf(&b, "_All files meet the %.0f%% coverage threshold._\n", threshold)
		return b.String()
	}
	fmt.Fprintf(&b, "%d file(s) below the %.0f%% threshold. Recommendation is architecture-aware (engine paths get higher priority than utility code).\n\n",
		len(attention), threshold)
	fmt.Fprintf(&b, "| File | Coverage | Recommendation |\n")
	fmt.Fprintf(&b, "|---|---:|---|\n")
	for _, f := range attention {
		fmt.Fprintf(&b, "| `%s` | %.1f%% | %s |\n", f.Path, f.Percent, recommend(f))
	}
	return b.String()
}
