// Code generated by cmd/hexdek-freya/gen_spellbook; DO NOT EDIT.
// Source: testdata/spellbook_generator_seed.json (21 combos)
// Regenerate with: go run ./cmd/hexdek-freya/gen_spellbook -in <path> -out cmd/hexdek-freya/spellbook_generated.go

package main

// generatedSpellbookCombos is the deduped-on-card-set Commander Spellbook
// import baseline shipped in the repo. Freya merges this on top of the
// hand-curated KnownCombos via allKnownCombos(); the runtime --spellbook
// cache layers further imports on top.
var generatedSpellbookCombos = []KnownCombo{
	{
		Name:        "Bloom Tender + Freed from the Real",
		Pieces:      []string{"Bloom Tender", "Freed from the Real"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Imported from Commander Spellbook (spbk-bloom-freed) — produces: Infinite colored mana. Bloom Tender taps for one mana of each color you control. Freed from the Real lets you pay U to untap. With 2+ colors including U, this is infinite mana.",
	},
	{
		Name:        "Bloom Tender + Pemmin's Aura",
		Pieces:      []string{"Bloom Tender", "Pemmin's Aura"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Imported from Commander Spellbook (spbk-bloom-pemmins) — produces: Infinite colored mana. Bloom Tender taps for one mana of each color. Pemmin's Aura lets you pay U to untap. Infinite colored mana.",
	},
	{
		Name:        "Bloom Tender + Umbral Mantle",
		Pieces:      []string{"Bloom Tender", "Umbral Mantle"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Imported from Commander Spellbook (spbk-bloom-umbral) — produces: Infinite colored mana. Bloom Tender + Umbral Mantle requires Bloom Tender to be power >= 4 (anthem). When met, generates infinite colored mana per color you control.",
	},
	{
		Name:        "Cloud of Faeries + Earthcraft + Squirrel Nest",
		Pieces:      []string{"Cloud of Faeries", "Earthcraft", "Squirrel Nest"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Imported from Commander Spellbook (spbk-cloud-earthcraft) — produces: Infinite creature tokens, Win the game. Cloud of Faeries untaps two lands; Earthcraft taps a creature to untap a land. Plus a sac outlet token engine, infinite ETBs.",
	},
	{
		Name:        "Devoted Druid + Vizier of Remedies",
		Pieces:      []string{"Devoted Druid", "Vizier of Remedies"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Imported from Commander Spellbook (spbk-devoted-vizier) — produces: Infinite green mana. Devoted Druid taps for G then puts a -1/-1 counter on itself to untap. Vizier of Remedies prevents the -1/-1 counter, enabling infinite green mana.",
	},
	{
		Name:        "Helm of Obedience + Leyline of the Void",
		Pieces:      []string{"Helm of Obedience", "Leyline of the Void"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Imported from Commander Spellbook (spbk-helm-leyline) — produces: Win the game. Same as Helm + Rest in Peace, using Leyline of the Void as the graveyard-replacement.",
	},
	{
		Name:        "Helm of Obedience + Rest in Peace",
		Pieces:      []string{"Helm of Obedience", "Rest in Peace"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Imported from Commander Spellbook (spbk-helm-rip) — produces: Win the game. Activate Helm of Obedience for X=0 with Rest in Peace on the battlefield. Each card milled is exiled, never satisfying the X creatures condition, milling the entire library.",
	},
	{
		Name:        "Mikaeus, the Unhallowed + Triskelion",
		Pieces:      []string{"Mikaeus, the Unhallowed", "Triskelion"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Imported from Commander Spellbook (spbk-mikaeus-triskelion) — produces: Win the game. Curated duplicate: Mikaeus + Triskelion (already in Freya's hand-curated set). Should be dropped at merge time.",
	},
	{
		Name:        "Mindcrank + Bloodchief Ascension",
		Pieces:      []string{"Mindcrank", "Bloodchief Ascension"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Imported from Commander Spellbook (spbk-mindcrank-bloodchief) — produces: Win the game. Activate Bloodchief Ascension's quest to start draining. Any 1 damage triggers Mindcrank for a mill, which counts as life loss for Bloodchief, which mills again. Infinite drain.",
	},
	{
		Name:        "Niv-Mizzet, Parun + Curiosity",
		Pieces:      []string{"Niv-Mizzet, Parun", "Curiosity"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Imported from Commander Spellbook (spbk-nivparun-curiosity) — produces: Win the game. Niv-Mizzet, Parun deals 1 damage when you draw, Curiosity makes you draw when Niv deals damage. Loop until opponents are dead.",
	},
	{
		Name:        "Niv-Mizzet, Parun + Ophidian Eye",
		Pieces:      []string{"Niv-Mizzet, Parun", "Ophidian Eye"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Imported from Commander Spellbook (spbk-nivparun-ophidian) — produces: Win the game. Niv-Mizzet damage triggers draw via Ophidian Eye (same draw-on-combat-damage shape adapted for Niv's noncombat ping).",
	},
	{
		Name:        "Niv-Mizzet, the Firemind + Curiosity",
		Pieces:      []string{"Niv-Mizzet, the Firemind", "Curiosity"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Imported from Commander Spellbook (spbk-nivfire-curiosity) — produces: Win the game. Niv-Mizzet, the Firemind + Curiosity: same loop as Parun variant.",
	},
	{
		Name:        "Pestermite + Kiki-Jiki, Mirror Breaker",
		Pieces:      []string{"Pestermite", "Kiki-Jiki, Mirror Breaker"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Imported from Commander Spellbook (spbk-pestermite-kiki) — produces: Infinite hasty creature tokens, Win the game. Kiki-Jiki copies Pestermite, copy untaps Kiki-Jiki, repeat for infinite hasty creature tokens.",
	},
	{
		Name:        "Pestermite + Splinter Twin",
		Pieces:      []string{"Pestermite", "Splinter Twin"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Imported from Commander Spellbook (spbk-pestermite-twin) — produces: Infinite hasty creature tokens, Win the game. Splinter Twin on Pestermite. Tap to make a hasty copy that untaps Pestermite. Repeat for infinite hasty fliers.",
	},
	{
		Name:        "Pili-Pala + Grand Architect",
		Pieces:      []string{"Pili-Pala", "Grand Architect"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Imported from Commander Spellbook (spbk-pili-grand) — produces: Infinite colored mana. Grand Architect makes Pili-Pala blue and pumps it. Tap Pili-Pala for two of any color, spend two to untap. Infinite colored mana.",
	},
	{
		Name:        "Power Artifact + Basalt Monolith",
		Pieces:      []string{"Power Artifact", "Basalt Monolith"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Imported from Commander Spellbook (spbk-power-basalt) — produces: Infinite colorless mana. Basalt Monolith costs {3} to untap with Power Artifact reducing the cost by {2}. Net 1 mana per untap, generating infinite colorless mana.",
	},
	{
		Name:        "Selvala, Heart of the Wilds + Umbral Mantle",
		Pieces:      []string{"Selvala, Heart of the Wilds", "Umbral Mantle"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Imported from Commander Spellbook (spbk-selvala-umbral) — produces: Infinite mana. Selvala, Heart of the Wilds: tap for mana equal to greatest power on battlefield. Umbral Mantle untaps for 3 mana if creature has power >= 4. With Selvala's power >= 4 (counter/anthem) this is infinite mana.",
	},
	{
		Name:        "Spike Feeder + Heliod, Sun-Crowned",
		Pieces:      []string{"Spike Feeder", "Heliod, Sun-Crowned"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Imported from Commander Spellbook (spbk-heliod-feeder) — produces: Infinite life. Spike Feeder gains 2 life, Heliod puts a +1/+1 counter on Spike Feeder (lifelink trigger). Remove two counters from Spike Feeder to gain 2 life. Infinite life.",
	},
	{
		Name:        "Time Sieve + Thopter Assembly",
		Pieces:      []string{"Time Sieve", "Thopter Assembly"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Imported from Commander Spellbook (spbk-time-sieve) — produces: Infinite turns. Thopter Assembly returns to hand at upkeep if you control no Thopter tokens, then ETBs creating 5 Thopters. Time Sieve sacrifices five artifacts for an extra turn. Infinite turns.",
	},
	{
		Name:        "Vizkopa Guildmage + Sanguine Bond",
		Pieces:      []string{"Vizkopa Guildmage", "Sanguine Bond"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Imported from Commander Spellbook (spbk-vizkopa-sang) — produces: Win the game. Vizkopa Guildmage activated: whenever you gain life this turn each opponent loses that much life. Sanguine Bond: when an opponent loses life you gain that much. Infinite drain.",
	},
	{
		Name:        "Walking Ballista + Heliod, Sun-Crowned",
		Pieces:      []string{"Walking Ballista", "Heliod, Sun-Crowned"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Imported from Commander Spellbook (spbk-heliod-ballista) — produces: Win the game. Curated duplicate: Heliod + Walking Ballista (already in Freya's hand-curated set).",
	},
}
