#!/usr/bin/env python3
"""Audit UnknownEffect raw_text phrases in ast_dataset.jsonl.

Walks the full dataset, extracts every node with ``__ast_type__ == "UnknownEffect"``,
counts unique raw_text values, and writes a markdown report with the top-N
phrases, their frequencies, and example card names.

Output: data/rules/unknown_effect_audit.md
"""

from __future__ import annotations

import json
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATASET = ROOT / "data" / "rules" / "ast_dataset.jsonl"
OUT = ROOT / "data" / "rules" / "unknown_effect_audit.md"

TOP_N = 200


def walk(node, unknown_out, card_name):
    """Recursively walk the AST, collecting UnknownEffect raw_text values."""
    if isinstance(node, dict):
        t = node.get("__ast_type__")
        if t == "UnknownEffect":
            raw = node.get("raw_text") or ""
            unknown_out.append((raw.strip().lower().rstrip("."), card_name))
            return
        for v in node.values():
            walk(v, unknown_out, card_name)
    elif isinstance(node, list):
        for x in node:
            walk(x, unknown_out, card_name)


def main():
    counter: Counter = Counter()
    examples: dict[str, list[str]] = defaultdict(list)
    total_rows = 0
    total_unknowns = 0

    with DATASET.open("r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            row = json.loads(line)
            name = row.get("name") or "?"
            unknowns: list[tuple[str, str]] = []
            walk(row.get("ast"), unknowns, name)
            for raw, n in unknowns:
                if not raw:
                    continue
                counter[raw] += 1
                if len(examples[raw]) < 6 and n not in examples[raw]:
                    examples[raw].append(n)
                total_unknowns += 1
            total_rows += 1

    distinct = len(counter)
    lines: list[str] = []
    lines.append("# UnknownEffect Raw-Text Audit")
    lines.append("")
    lines.append("Generated by ``scripts/audit_unknown_effects.py``.")
    lines.append("")
    lines.append("- Rows scanned: **{:,}**".format(total_rows))
    lines.append("- Total UnknownEffect nodes: **{:,}**".format(total_unknowns))
    lines.append("- Distinct raw_text values: **{:,}**".format(distinct))
    lines.append("")
    lines.append("## Wave 1a promotion (2026-04-16)")
    lines.append("")
    lines.append(
        "``scripts/extensions/a_wave1a_promotions.py`` targets the phrase "
        "families below. Each promoted phrase emits a typed AST node "
        "(``Draw``, ``Destroy``, ``Recurse``, ``Choice``, ``CreateToken``, "
        "``LoseGame``, ``Mill``, ``Reveal``, ``Reanimate``, ``Tutor``, "
        "``Fight``, ``Conditional``, ``Optional_``, ``GrantAbility``) or a "
        "``Modification`` stub with a discriminator kind, instead of an "
        "opaque ``UnknownEffect``. See the module docstring for per-phrase "
        "example cards and ``tests/test_wave1a_promotions.py`` for the "
        "regression guard."
    )
    lines.append("")
    lines.append("Before/after (Wave 1a):")
    lines.append("")
    lines.append("| Metric | Before | After | Δ |")
    lines.append("|---|---:|---:|---:|")
    lines.append("| UnknownEffect nodes | 7,028 | {:,} | {:+,} |".format(total_unknowns, total_unknowns - 7028))
    lines.append("| Distinct raw_text | 5,073 | {:,} | {:+,} |".format(distinct, distinct - 5073))
    lines.append("")
    lines.append("## Top {} Phrases by Frequency (post-promotion)".format(TOP_N))
    lines.append("")
    lines.append("| # | Count | Phrase | Example Cards |")
    lines.append("|---|-------|--------|----------------|")
    for i, (phrase, cnt) in enumerate(counter.most_common(TOP_N), 1):
        phrase_disp = phrase.replace("|", "\\|")
        if len(phrase_disp) > 160:
            phrase_disp = phrase_disp[:157] + "..."
        ex = "; ".join(examples[phrase][:4])
        ex = ex.replace("|", "\\|")
        lines.append(f"| {i} | {cnt} | `{phrase_disp}` | {ex} |")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")
    print(f"  distinct phrases: {distinct:,}")
    print(f"  total nodes: {total_unknowns:,}")
    print(f"  top 20:")
    for phrase, cnt in counter.most_common(20):
        print(f"    {cnt:5d}  {phrase[:120]}")


if __name__ == "__main__":
    main()
