package main

// KnownCombo is a confirmed combo that Freya should always flag
// with 100% confidence when all pieces are in a deck.
type KnownCombo struct {
	Name        string
	Pieces      []string // card names (all must be present)
	Type        string   // "true_infinite" or "determined"
	Mandatory   bool     // are the triggers mandatory?
	Description string
	Outlets     []string // known cards that convert this into a win
	Stops       []string // known cards that break the loop
}

var KnownCombos = []KnownCombo{
	// ── True Infinites (mandatory) ──
	{
		Name:        "Polyraptor + Marauding Raptor",
		Pieces:      []string{"Polyraptor", "Marauding Raptor"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Polyraptor ETB → Marauding Raptor deals 2 → Enrage creates copy → copy ETBs → infinite loop. Game draws without outlet or stop.",
		Outlets:     []string{"Warstorm Surge", "Impact Tremors", "Purphoros, God of the Forge", "Terror of the Peaks", "Goblin Bombardment", "Altar of Dementia"},
		Stops:       []string{"Marauding Raptor itself can be sacrificed", "Any instant-speed removal on either piece"},
	},
	{
		Name:        "Exquisite Blood + Sanguine Bond",
		Pieces:      []string{"Exquisite Blood", "Sanguine Bond"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Any life gain or opponent life loss triggers infinite drain loop. Kills all opponents.",
		Outlets:     []string{},
		Stops:       []string{"Remove either enchantment in response to the first trigger"},
	},
	{
		Name:        "Exquisite Blood + Enduring Tenacity",
		Pieces:      []string{"Exquisite Blood", "Enduring Tenacity"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Enduring Tenacity: lifegain → opponent loses life. Exquisite Blood: opponent loses life → you gain life. Infinite mandatory drain loop. Self-recurring (returns as enchantment on death).",
		Outlets:     []string{},
		Stops:       []string{"Remove either piece in response to first trigger", "Enduring Tenacity can be killed but returns as enchantment — need exile"},
	},
	{
		Name:        "Exquisite Blood + Vito, Thorn of the Dusk Rose",
		Pieces:      []string{"Exquisite Blood", "Vito, Thorn of the Dusk Rose"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Vito: lifegain → opponent loses life. Exquisite Blood: opponent loses life → you gain life. Same loop as Sanguine Bond but on a creature.",
		Outlets:     []string{},
		Stops:       []string{"Remove either piece"},
	},
	{
		Name:        "Exquisite Blood + Marauding Blight-Priest",
		Pieces:      []string{"Exquisite Blood", "Marauding Blight-Priest"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Blight-Priest: lifegain → each opponent loses 1. Exquisite Blood: opponent loses life → you gain life. Infinite drain.",
		Outlets:     []string{},
		Stops:       []string{"Remove either piece"},
	},
	{
		Name:        "Exquisite Blood + Defiant Bloodlord",
		Pieces:      []string{"Exquisite Blood", "Defiant Bloodlord"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Bloodlord: lifegain → opponent loses that much. Exquisite Blood: opponent loses life → you gain. Infinite drain loop.",
		Outlets:     []string{},
		Stops:       []string{"Remove either piece"},
	},
	{
		Name:        "Mikaeus + Triskelion",
		Pieces:      []string{"Mikaeus, the Unhallowed", "Triskelion"},
		Type:        "true_infinite",
		Mandatory:   true,
		Description: "Remove counters from Triskelion to deal damage, it dies, Undying returns it with +1/+1 counter, remove counters again. Infinite damage.",
		Outlets:     []string{}, // self-contained kill
		Stops:       []string{"Exile either piece", "Graveyard hate"},
	},
	{
		Name:        "Kiki-Jiki + Zealous Conscripts",
		Pieces:      []string{"Kiki-Jiki, Mirror Breaker", "Zealous Conscripts"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Kiki copies Conscripts, copy untaps Kiki, repeat for infinite hasty tokens.",
		Outlets:     []string{}, // tokens attack for the win
		Stops:       []string{"Remove Kiki-Jiki in response"},
	},
	{
		Name:        "Kiki-Jiki + Felidar Guardian",
		Pieces:      []string{"Kiki-Jiki, Mirror Breaker", "Felidar Guardian"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Kiki copies Felidar, copy blinks Kiki, untapped Kiki copies again. Infinite hasty tokens.",
		Outlets:     []string{},
		Stops:       []string{"Remove either piece"},
	},
	{
		Name:        "Splinter Twin + Deceiver Exarch",
		Pieces:      []string{"Splinter Twin", "Deceiver Exarch"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Enchanted Exarch taps to create copy, copy untaps original, repeat. Infinite hasty tokens.",
		Outlets:     []string{},
		Stops:       []string{"Remove enchantment or creature"},
	},
	// ── Determined Infinites (optional) ──
	{
		Name:        "Basalt Monolith + Kinnan",
		Pieces:      []string{"Basalt Monolith", "Kinnan, Bonder Prodigy"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Tap Basalt for 3+1 (Kinnan doubles), pay 3 to untap. Net +1 mana each cycle. Infinite colorless mana.",
		Outlets:     []string{"Any mana sink: Walking Ballista, Staff of Domination, etc."},
		Stops:       []string{},
	},
	{
		Name:        "Isochron Scepter + Dramatic Reversal",
		Pieces:      []string{"Isochron Scepter", "Dramatic Reversal"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Imprint Dramatic Reversal on Scepter. Activate Scepter (2 mana), untap all nonland permanents including Scepter. Net mana with 3+ mana rocks.",
		Outlets:     []string{"Any mana sink", "Aetherflux Reservoir for storm count"},
		Stops:       []string{},
	},
	{
		Name:        "Thoracle + Demonic Consultation",
		Pieces:      []string{"Thassa's Oracle", "Demonic Consultation"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Cast Consultation naming a card not in deck, exile library. Oracle ETB with empty library = win.",
		Outlets:     []string{}, // self-contained win
		Stops:       []string{"Stifle the ETB", "Trickbind", "Kill Oracle in response"},
	},
	{
		Name:        "Thoracle + Tainted Pact",
		Pieces:      []string{"Thassa's Oracle", "Tainted Pact"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Tainted Pact with singleton deck exiles entire library. Oracle ETB = win.",
		Outlets:     []string{},
		Stops:       []string{"Stifle", "Kill Oracle"},
	},
	{
		Name:        "Walking Ballista + Heliod",
		Pieces:      []string{"Walking Ballista", "Heliod, Sun-Crowned"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Ballista with lifelink from Heliod. Remove counter to deal 1, gain 1 life, Heliod puts counter back. Infinite damage.",
		Outlets:     []string{},
		Stops:       []string{"Remove either piece", "Prevent lifelink"},
	},
	{
		Name:        "Ragost Strongbull Loop",
		Pieces:      []string{"Penregon Strongbull", "Crime Novelist", "Nuka-Cola Vending Machine"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Sac artifact with Strongbull (1 damage each opp), Novelist adds {R}, Nuka-Cola creates Treasure (Food via Ragost). Pay {R} to repeat.",
		Outlets:     []string{},
		Stops:       []string{"Remove any piece", "Stifle Nuka-Cola trigger"},
	},
	{
		Name:        "Phyrexian Altar + Gravecrawler",
		Pieces:      []string{"Phyrexian Altar", "Gravecrawler"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Sac Gravecrawler for {B}, recast from graveyard (needs a Zombie). Infinite death/ETB triggers, infinite {B}.",
		Outlets:     []string{"Blood Artist", "Zulaport Cutthroat", "Diregraf Captain"},
		Stops:       []string{"Graveyard hate", "Remove Zombie requirement"},
	},
	{
		Name:        "Dockside + Temur Sabertooth",
		Pieces:      []string{"Dockside Extortionist", "Temur Sabertooth"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Bounce Dockside with Sabertooth ({1}{G}), recast for Treasures. Net positive if opponents have 3+ artifacts/enchantments.",
		Outlets:     []string{"Any mana sink"},
		Stops:       []string{"Remove either piece"},
	},
	{
		Name:        "Food Chain + Eternal Creature",
		Pieces:      []string{"Food Chain"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Exile creature from command zone for mana, recast with extra mana. Infinite ETBs + mana (creature spells only).",
		Outlets:     []string{"Thassa's Oracle", "Walking Ballista (via infinite mana)", "Aetherflux Reservoir"},
		Stops:       []string{"Remove Food Chain"},
	},
	// ── Universal Combo Enablers ──
	{
		Name:        "Displacer Kitten + Sol Ring",
		Pieces:      []string{"Displacer Kitten", "Sol Ring"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Cast any noncreature spell → blink Sol Ring (enters untapped) → net +1 mana per loop. Infinite mana with any 1-cost noncreature spell.",
		Outlets:     []string{"Walking Ballista", "Aetherflux Reservoir", "Thassa's Oracle", "Staff of Domination"},
		Stops:       []string{"Remove Kitten", "Stifle the blink trigger"},
	},
	{
		Name:        "Displacer Kitten + Mana Crypt",
		Pieces:      []string{"Displacer Kitten", "Mana Crypt"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Cast any noncreature spell → blink Mana Crypt (enters untapped) → net +1 mana per loop. Infinite colorless mana.",
		Outlets:     []string{"Walking Ballista", "Aetherflux Reservoir", "Staff of Domination"},
		Stops:       []string{"Remove Kitten"},
	},
	{
		Name:        "Displacer Kitten + Sensei's Divining Top",
		Pieces:      []string{"Displacer Kitten", "Sensei's Divining Top"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Tap Top to draw → recast Top for {1} → Kitten blinks a mana rock → net mana + draw entire deck. Infinite draw with any mana rock.",
		Outlets:     []string{"Thassa's Oracle", "Aetherflux Reservoir", "Laboratory Maniac"},
		Stops:       []string{"Remove Kitten or Top"},
	},
	{
		Name:        "Displacer Kitten + Isochron Scepter",
		Pieces:      []string{"Displacer Kitten", "Isochron Scepter"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Activate Scepter (cast imprint) → Kitten blinks Scepter (resets) → repeat. Infinite casts of imprinted spell.",
		Outlets:     []string{"Dramatic Reversal (imprinted)", "Aetherflux Reservoir"},
		Stops:       []string{"Remove Kitten or Scepter"},
	},
	{
		Name:        "Deadeye Navigator + Peregrine Drake",
		Pieces:      []string{"Deadeye Navigator", "Peregrine Drake"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Soulbond Deadeye with Drake. Pay {1}{U} to blink Drake → untap 5 lands → net +3 mana per loop. Infinite mana.",
		Outlets:     []string{"Any mana sink", "Thassa's Oracle", "Walking Ballista"},
		Stops:       []string{"Remove either piece", "Stifle ETB"},
	},
	{
		Name:        "Deadeye Navigator + Palinchron",
		Pieces:      []string{"Deadeye Navigator", "Palinchron"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Soulbond Deadeye with Palinchron. Pay {1}{U} to blink → untap 7 lands → net +5 mana. Infinite mana.",
		Outlets:     []string{"Any mana sink"},
		Stops:       []string{"Remove either piece"},
	},
	{
		Name:        "Deadeye Navigator + Dockside Extortionist",
		Pieces:      []string{"Deadeye Navigator", "Dockside Extortionist"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Soulbond Deadeye with Dockside. Pay {1}{U} to blink Dockside → create Treasures. Infinite mana if opponents have 3+ artifacts/enchantments.",
		Outlets:     []string{"Any mana sink", "Aetherflux Reservoir"},
		Stops:       []string{"Remove either piece", "Opponents remove their artifacts/enchantments"},
	},
	{
		Name:        "Deadeye Navigator + Eternal Witness",
		Pieces:      []string{"Deadeye Navigator", "Eternal Witness"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Blink Witness → return any card from graveyard. With infinite mana, return and recast anything. Infinite recursion.",
		Outlets:     []string{"Any win condition in graveyard"},
		Stops:       []string{"Remove either piece", "Graveyard exile"},
	},
	{
		Name:        "Deadeye Navigator + Gray Merchant of Asphodel",
		Pieces:      []string{"Deadeye Navigator", "Gray Merchant of Asphodel"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Blink Gray Merchant → drain each opponent for devotion. With infinite mana, infinite drain. Kills the table.",
		Outlets:     []string{},
		Stops:       []string{"Remove either piece"},
	},
	// ── Lab Man / Thoracle Lines ──
	{
		Name:        "Thassa's Oracle + Hermit Druid",
		Pieces:      []string{"Thassa's Oracle", "Hermit Druid"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Hermit Druid with no basic lands mills entire library. Oracle ETB with empty library = win.",
		Outlets:     []string{},
		Stops:       []string{"Kill Hermit Druid in response", "Stifle Oracle ETB", "Play basic lands to stop Druid"},
	},
	{
		Name:        "Laboratory Maniac + Demonic Consultation",
		Pieces:      []string{"Laboratory Maniac", "Demonic Consultation"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Cast Consultation naming a card not in deck, exile library. Draw a card with Lab Man in play = win.",
		Outlets:     []string{},
		Stops:       []string{"Kill Lab Man before drawing", "Counter the draw spell"},
	},
	{
		Name:        "Laboratory Maniac + Tainted Pact",
		Pieces:      []string{"Laboratory Maniac", "Tainted Pact"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Tainted Pact with singleton deck exiles entire library. Draw a card with Lab Man in play = win.",
		Outlets:     []string{},
		Stops:       []string{"Kill Lab Man before drawing"},
	},
	{
		Name:        "Jace, Wielder of Mysteries + Demonic Consultation",
		Pieces:      []string{"Jace, Wielder of Mysteries", "Demonic Consultation"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Cast Consultation naming a card not in deck, exile library. Activate Jace's +1 to draw with empty library = win.",
		Outlets:     []string{},
		Stops:       []string{"Kill Jace before +1 resolves", "Counter Consultation"},
	},
	{
		Name:        "Jace, Wielder of Mysteries + Tainted Pact",
		Pieces:      []string{"Jace, Wielder of Mysteries", "Tainted Pact"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Tainted Pact with singleton deck exiles entire library. Activate Jace's +1 = win.",
		Outlets:     []string{},
		Stops:       []string{"Kill Jace before +1"},
	},
	// ── Doomsday Piles ──
	{
		Name:        "Doomsday + Thassa's Oracle",
		Pieces:      []string{"Doomsday", "Thassa's Oracle"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Doomsday sets up a 5-card pile with Oracle on top. Draw into Oracle, cast with 0-2 cards in library = win.",
		Outlets:     []string{},
		Stops:       []string{"Counter Doomsday", "Counter Oracle", "Stifle Oracle ETB"},
	},
	{
		Name:        "Doomsday + Laboratory Maniac",
		Pieces:      []string{"Doomsday", "Laboratory Maniac"},
		Type:        "determined",
		Mandatory:   false,
		Description: "Doomsday leaves 5 cards in library. Lab Man + draw through the pile = win when library is empty.",
		Outlets:     []string{},
		Stops:       []string{"Counter Doomsday", "Kill Lab Man before final draw"},
	},
	// ── Purphoros / Impact Tremors Lines ──
	{
		Name:        "Purphoros + Any Token Engine",
		Pieces:      []string{"Purphoros, God of the Forge"},
		Type:        "synergy",
		Mandatory:   false,
		Description: "Every creature ETB deals 2 to each opponent. With infinite tokens = infinite damage.",
		Outlets:     []string{},
		Stops:       []string{},
	},
	{
		Name:        "Impact Tremors + Any Token Engine",
		Pieces:      []string{"Impact Tremors"},
		Type:        "synergy",
		Mandatory:   false,
		Description: "Every creature ETB deals 1 to each opponent.",
		Outlets:     []string{},
		Stops:       []string{},
	},
	// ── ETB Doublers (not blink but same category) ──
	{
		Name:        "Panharmonicon + Any ETB",
		Pieces:      []string{"Panharmonicon"},
		Type:        "synergy", // not a loop, just doubled value
		Mandatory:   false,
		Description: "Doubles all artifact and creature ETB triggers. Universal value multiplier.",
		Outlets:     []string{},
		Stops:       []string{},
	},
	{
		Name:        "Yarok + Any ETB",
		Pieces:      []string{"Yarok, the Desecrated"},
		Type:        "synergy",
		Mandatory:   false,
		Description: "Doubles ALL permanent ETB triggers. Even stronger than Panharmonicon.",
		Outlets:     []string{},
		Stops:       []string{},
	},
	// ── Blink Enablers ──
	{
		Name:        "Conjurer's Closet + Any Value ETB",
		Pieces:      []string{"Conjurer's Closet"},
		Type:        "synergy",
		Mandatory:   false,
		Description: "Free blink every end step. Repeatable value engine with any ETB creature.",
		Outlets:     []string{},
		Stops:       []string{},
	},
	{
		Name:        "Thassa, Deep-Dwelling + Any Value ETB",
		Pieces:      []string{"Thassa, Deep-Dwelling"},
		Type:        "synergy",
		Mandatory:   false,
		Description: "Free blink every end step on an indestructible body. Premium blink engine.",
		Outlets:     []string{},
		Stops:       []string{},
	},
	{
		Name:        "Ephemerate + Any Value ETB",
		Pieces:      []string{"Ephemerate"},
		Type:        "synergy",
		Mandatory:   false,
		Description: "1-mana blink with rebound — two blinks for one card. Extremely efficient.",
		Outlets:     []string{},
		Stops:       []string{},
	},
}
