package analytics

import (
	"sort"
	"strings"
)

// RankCards aggregates card performance across multiple game analyses and
// returns cards sorted by win contribution (descending). This answers
// "which cards actually matter in this deck?"
func RankCards(analyses []*GameAnalysis) []CardRanking {
	if len(analyses) == 0 {
		return nil
	}

	// Accumulate per-card stats.
	type cardAccum struct {
		name           string
		gamesPlayed    int // games where this card appeared in a player's card list
		timesCast      int
		gamesWon       int     // games where this card's controller won
		winContribSum  int     // count of wins where ContributedToWin was true
		turnCastSum    float64 // sum of TurnCast (for avg calculation, only non-zero)
		turnCastCount  int
		damageSum      int
		killsSum       int
		deadInHand     int // games where TurnCast == 0 (never cast)
		counteredCount int // total times countered
		castAttempts   int // total times cast (for countered rate)
		killShots      int // wins where this card was the WinningCard
	}

	cards := make(map[string]*cardAccum)

	for _, ga := range analyses {
		if ga == nil {
			continue
		}

		// Track which cards appeared per-seat this game to avoid
		// double-counting the same card across seats.
		for seatIdx := range ga.Players {
			pa := &ga.Players[seatIdx]
			won := pa.Won

			for i := range pa.CardsPlayed {
				cp := &pa.CardsPlayed[i]
				acc, ok := cards[cp.Name]
				if !ok {
					acc = &cardAccum{name: cp.Name}
					cards[cp.Name] = acc
				}

				acc.gamesPlayed++
				if cp.TurnCast > 0 {
					acc.timesCast++
					acc.turnCastSum += float64(cp.TurnCast)
					acc.turnCastCount++
					acc.castAttempts++
				} else if cp.WasCountered {
					// Was cast but countered -- still a cast attempt.
					acc.castAttempts++
				} else if !cp.IsLand && !cp.IsToken && !isTokenByName(cp.Name) {
					// Only count non-land, non-token cards as "dead in hand."
					// Lands are played (not cast), and tokens are created
					// (not drawn/cast), so they shouldn't be in dead card lists.
					acc.deadInHand++
				}

				if cp.WasCountered {
					acc.counteredCount++
				}

				acc.damageSum += cp.DamageDealt
				acc.killsSum += cp.KillsAttributed

				if won {
					acc.gamesWon++
					if cp.ContributedToWin {
						acc.winContribSum++
					}
				}

				// Kill shot: this card was the WinningCard.
				if won && ga.WinningCard == cp.Name {
					acc.killShots++
				}
			}
		}
	}

	// Convert to CardRanking slice.
	rankings := make([]CardRanking, 0, len(cards))
	for _, acc := range cards {
		cr := CardRanking{
			Name:        acc.name,
			GamesPlayed: acc.gamesPlayed,
			TimesCast:   acc.timesCast,
			GamesWon:    acc.gamesWon,
		}

		if acc.gamesWon > 0 {
			cr.WinContribution = float64(acc.winContribSum) / float64(acc.gamesWon)
		}
		if acc.turnCastCount > 0 {
			cr.AvgTurnCast = acc.turnCastSum / float64(acc.turnCastCount)
		}
		if acc.gamesPlayed > 0 {
			cr.AvgDamageDealt = float64(acc.damageSum) / float64(acc.gamesPlayed)
			cr.AvgKills = float64(acc.killsSum) / float64(acc.gamesPlayed)
			cr.DeadInHandRate = float64(acc.deadInHand) / float64(acc.gamesPlayed)
		}
		if acc.castAttempts > 0 {
			cr.CounteredRate = float64(acc.counteredCount) / float64(acc.castAttempts)
		}
		if acc.gamesWon > 0 {
			cr.KillShotRate = float64(acc.killShots) / float64(acc.gamesWon)
		}

		rankings = append(rankings, cr)
	}

	// Sort by GamesWon desc, then by TimesCast desc as tiebreaker.
	sort.SliceStable(rankings, func(i, j int) bool {
		if rankings[i].GamesWon != rankings[j].GamesWon {
			return rankings[i].GamesWon > rankings[j].GamesWon
		}
		if rankings[i].TimesCast != rankings[j].TimesCast {
			return rankings[i].TimesCast > rankings[j].TimesCast
		}
		return rankings[i].AvgDamageDealt > rankings[j].AvgDamageDealt
	})

	return rankings
}

// isTokenByName detects token cards by their name pattern. Token cards
// generated by the engine typically have "Token" in their name (e.g.,
// "creature token colorless spirit Token") or start with common token
// prefixes.
func isTokenByName(name string) bool {
	lower := strings.ToLower(name)
	return strings.Contains(lower, "token")
}
